include $(TOPDIR)/.config

define WEMO_APP
$$(OUTPUT): $$(OBJS)
	$$(CC) $$(LDFLAGS) -o $$@ $$^

clean:
	rm -f $$(OUTPUT) $$(OBJS)
endef

define WEMO_LIB
$$(OUTPUT): $$(OBJS)
	$$(CC) -shared $$(LDFLAGS) -o $$@ $$^

clean :
	rm -f $$(OUTPUT) $$(OBJS)
endef

ifeq ($(CONFIG_TOOLCHAIN_ROOT),"/opt/buildroot-gcc342")
EXTRA_CFLAGS += -Wall -D_OPENWRT_ -D_REENTRANT -D__HLOGS__
else
EXTRA_CFLAGS += -Wall --honour-copts -D_OPENWRT_ -D_REENTRANT -D__HLOGS__
endif

ifneq ($(CONFIG_WEMO_DIAG),)
EXTRA_CFLAGS += -DDMALLOC -DDMALLOC_FUNC_CHECK
EXTRA_LDFLAGS += -ldmallocth
endif

ifeq ($(CONFIG_WEMO_PRODUCTION_IMAGE),)
EXTRA_CFLAGS += -g
EXTRA_CFLAGS += -DNDEBUG
EXTRA_CFLAGS += -DDEBUG_ENABLE
endif

ifneq ($(CONFIG_PACKAGE_WeMo_Jarden),)
EXTRA_CFLAGS += -DPRODUCT_WeMo_Jarden
endif

ifneq ($(CONFIG_PACKAGE_WeMo_Smart),)
EXTRA_CFLAGS += -DPRODUCT_WeMo_Smart
EXTRA_CFLAGS += -DWeMo_SMART_SETUP
EXTRA_CFLAGS += -DEXTERN_WIFI
endif

ifneq ($(CONFIG_PACKAGE_WeMo_Link),)
EXTRA_CFLAGS += -DPRODUCT_WeMo_LEDLight -DWeMo_SMART_SETUP -DSIMULATED_OCCUPANCY
EXTRA_CFLAGS += -DNEW_BOARD
ifeq ($(CONFIG_WEMO_PRODUCTION_IMAGE),)
EXTRA_CFLAGS += -DBOARD_DVT
endif
endif

ifneq ($(CONFIG_PACKAGE_WeMo_SNS),)
EXTRA_CFLAGS += -DPRODUCT_WeMo_SNS -DSIMULATED_OCCUPANCY -DWeMo_SMART_SETUP
EXTRA_CFLAGS += -DNEW_BOARD
ifeq ($(CONFIG_WEMO_PRODUCTION_IMAGE),)
EXTRA_CFLAGS += -DBOARD_DVT
endif
endif

ifneq ($(CONFIG_PACKAGE_WeMo_Insight),)
EXTRA_CFLAGS += -DPRODUCT_WeMo_Insight -DSIMULATED_OCCUPANCY -DWeMo_SMART_SETUP
ifeq ($(CONFIG_WEMO_PRODUCTION_IMAGE),)
EXTRA_CFLAGS += -DBOARD_EVT
else
EXTRA_CFLAGS += -DBOARD_PVT
endif
ifneq ($(CONFIG_TARGET_rt288x_WemoInsightCR),)
EXTRA_CFLAGS += -DPRODUCT_WeMo_InsightCR
endif
endif

ifneq ($(CONFIG_PACKAGE_WeMo_Light),)
EXTRA_CFLAGS += -DPRODUCT_WeMo_Light -DSIMULATED_OCCUPANCY -DWeMo_SMART_SETUP -DLONG_PRESS_SUPPORTED
EXTRA_CFLAGS += -DNEW_BOARD
ifeq ($(CONFIG_WEMO_PRODUCTION_IMAGE),)
EXTRA_CFLAGS += -DBOARD_DVT
endif
endif

ifneq ($(CONFIG_PACKAGE_WeMo_NetCam),)
EXTRA_CFLAGS += -DPRODUCT_WeMo_NetCam
EXTRA_CFLAGS += -DWeMo_SMART_SETUP
EXTRA_CFLAGS += -DEXTERN_WIFI
ifeq ($(CONFIG_NETCAM_HD_V1),y)
	EXTRA_CFLAGS += -DNETCAM_HD_V1
endif
ifeq ($(CONFIG_NETCAM_HD_V2),y)
	EXTRA_CFLAGS += -DNETCAM_HD_V2
endif
ifeq ($(CONFIG_NETCAM_LS),y)
	EXTRA_CFLAGS += -DNETCAM_LS
endif
ifeq ($(CONFIG_NETCAM_NetCam),y)
	EXTRA_CFLAGS += -DNETCAM_NetCam
endif
endif
